### ISSUE TITLE
ngrok recipes

### ISSUE THREAD

**Issue by macmule** [autopkg/zentral-recipes#23]
Hi folks,

I started rejigging the ngrok recipes, and ended up completely rewriting - https://github.com/autopkg/dataJAR-recipes/tree/master/ngrok

A custom processor is used to get the version from the binary, for example.

Up to you, but you folks could deprecate your ngrok recipes I created.. up to you.

**Comment by headmin** [comment]
thanks ben, yes we will clean up and deprecate
