### ISSUE TITLE
Nova download recipe will not work when new updates are released

### ISSUE THREAD

**Issue by homebysix** [autopkg/zentral-recipes#6]
The download URL used by the Nova download recipe is static, and won't work for versions other than 1.0.

I had Nova recipes waiting in the wings for the official release — if you want, I could post and maintain mine, or I could submit a PR to yours that utilizes URLTextSearcher. Up to you.

**Comment by headmin** [comment]
HI Elliot,

thanks to reach out - yes this was a quick shot and late evening tasks to get Nova rolling here.

Sorry to create extra hoops on that - yes a PR very is welcome of course !!

**Comment by homebysix** [comment]
Sounds good; https://github.com/autopkg/zentral-recipes/pull/7 submitted.
